version: '3.9'
services:
  consul:
    image: consul:1.15.2
    ports:
      - "8500:8500"
    command: agent -dev -client=0.0.0.0 -config-file=consul.json
    volumes:
      - ./consul.json:/consul.json

  prometheus:
    image: quay.io/prometheus/prometheus:v2.44.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml