global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "consul-example"
    consul_sd_configs:
      - server: 'consul:8500'
    relabel_configs:
      - action: keep
        source_labels: [__meta_consul_service]
        regex: api