global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "api"
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: [
        "localhost:8080",
        "localhost:8081",
        "localhost:8082"
      ]
